###
POST http://127.0.0.1:5000/parser/start
Content-Type: application/json

{
  "parserName": "msudrf/sudebnoye-deloproizvodstvo",
  "inputData": {
    "searchText": "фамилия имя отчество"
  }
}

###
POST https://shp-parsing.ydnnov.ru/api/parser/start
Content-Type: application/json

{
  "parserName": "msudrf/sudebnoye-deloproizvodstvo",
  "inputData": {
    "searchText": "фамилия имя отчество"
  }
}
