###
POST http://127.0.0.1:5000/parser-task
Content-Type: application/json

{
  "parserKey": "fssp/",
  "inputItems": [
    {
      "fio": "Фролов Сергей Павлович",
      "dob": "27.02.1963",
      "reg": "Саратовская область",
      "timeout": 30000
    },
    {
      "fio": "Ситникова Светлана Александровна",
      "dob": "08.03.1969",
      "reg": "Саратовская область",
      "timeout": 30000
    },
    {
      "fio": "Потылицына Юлия Анатольевна",
      "dob": "25.07.1971",
      "reg": "Саратовская область"
    }
  ]
}
